#!/bin/bash
# $(id-u)checks if the script is being run by the root user 
if [ "$(id -u)" != "0" ]; 
  then
  echo "This script must be run as root or with sudo."
  exit 1
fi
# Switch to the "betty" user
su betty
